### ISSUE TITLE
Make background image customisable

### ISSUE THREAD

**Issue by tigris** [jkueh/aws-rolex#8] opened 2021-12-03 02:32 UTC
It'd be cool if I could configure this plugin to use any arbitrary image as the background, either as a http(s) url or file:// uri.

**Comment by adrianmace** [comment] 2021-12-03 02:39
👍🏻

**Comment by jkueh** [comment] 2021-12-03 02:51
Duplicate of #1, good extra detail 👍

**Comment by jkueh** [comment] 2021-12-07 12:20
Resolved by #9

**Closed as completed by jkueh** 2021-12-07 12:20 UTC
